src/math/Background.cc
src/math/BackgroundMI.cc
tests/background.py

Background discarded the xy0 of the image when it was constructed from an image
and calling getImage(bbox) required that bbox be local, as well. This fixes that problem.
tests/background.py includes two new tests for these changes, plus some minor tweaks
to make the pyflakes linter happier.
Improve a change to a test to make the linter happier

Review for DM-1680: Change Background to use the xy0 of the image bbox

---

include/lsst/afw/math/Statistics.h
src/math/Statistics.cc
tests/statistics.py

If the image and mask don't have the same size, we can get a NAN
result if all pixels in the lower-left are masked. This patch adds
a check on the size of all images to catch accidental user errors.

Review for DM-4881 (Statistics: assert that images have the same size)

---

src/formatters/TanWcsFormatter.cc
src/formatters/WcsFormatter.cc
tests/wcs1.py

For ICRS coordinates, EQUINOX is not required. Previously, we wrote a nonsense
number, but this confused some FITS readers (notably DS9 7.4). Now, we write
nothing.

Review of DM-5206: Avoid writing garbage EQUINOX to FITS.

---

include/lsst/afw/image/Calib.h
include/lsst/afw/math/Interpolate.h
include/lsst/afw/table/Match.h
python/lsst/afw/display/Rgb.h
python/lsst/afw/display/SConscript
python/lsst/afw/display/displayLib.i
python/lsst/afw/display/rgb.py
python/lsst/afw/display/scaling.cc
python/lsst/afw/display/utils.py
python/lsst/afw/geom/Box.i
python/lsst/afw/image/Calib.i
python/lsst/afw/table/Match.i
src/detection/Footprint.cc
src/image/Calib.cc
src/math/Interpolate.cc
src/table/Match.cc
tests/background.py
tests/exposure.py
tests/interpolate.py
tests/rgb.py
tests/sourceMatch.py
tests/ticket2707.py

Review of cherry-picked HSC commits to be merged.

DM-5280: Port afw changesets to LSST

---

include/lsst/afw/geom/CoordinateBase.h
include/lsst/afw/geom/Extent.h
include/lsst/afw/geom/Point.h
include/lsst/afw/image/MaskedImage.h
src/math/Statistics.cc

Excludes MaskedImage.h due to problems with boost::gil

Migrate boost::tuple to std::tuple

---

ups/afw.table

Tests appear to be depending on astropy; adding the astropy EUPS package as a dependency.

Add dependency on astropy

---

python/lsst/afw/table/Base.i
python/lsst/afw/table/_syntax.py
python/lsst/afw/table/specializations.i
tests/testAstropyTableViews.py

This adds an `asAstropy` method to get a `astropy.table.Table` or `astropy.table.QTable` view directly, as well as an `__astropy_table__` that will allow the Astropy table constructors to accept LSST `Catalog` objects (once astropy/astropy#4885 is complete).
The astropy PR has not quite been finalized, but I'm confident that any further changes will be minor, and hence it should be fine to review this now.  I will delay the merge of this ticket until the astropy PR is finalized (they also have a feature freeze this weekend, so I don't think we'll have to wait long).

Add Astropy view support to afw.table (DM-5641)

---

python/lsst/afw/table/__init__.py
python/lsst/afw/table/utils.py
tests/testTableUtils.py

Add two utility functions to lsst.afw.table:
updateRefCentroids and updateSourceCoords.
Add a unit test for these functions testTableUtils.py
(since the functions are defined in new module lsst.afw.table.utils)

Add updateRefCentroids and updateSourceCoords

---

python/lsst/afw/display/interface.py
tests/display.py
ups/afw.table

_callbacks property was missing an underscore.

DM-6613: Typo in afw/display/interface.py

---

python/lsst/afw/table/Catalog.i

Introduce a workaround to prevent infinite recursion in the swig
catalog bindings

Add temporary workaround for DM-7377

---

tests/background.cc
tests/statistics.cc

There is logic in the SConscript file to disable tests that use
afwdata but this logic does not get enabld when testExectuables.py
is run or if a user runs the test from the command line. This
patch adds additional skipping logic inside the test without
affecting the scons logic.

Skip test if afwdata is not available

---

src/image/Calib.cc
src/image/ExposureInfo.cc
tests/testColor.py

Specify time system for DateTime(isoString, system)
and DateTime.toString(system)

Specify time system when needed

---

python/lsst/afw/display/interface.py

show() is used in jupiter-enabled devices which need a value to display.

afw/DM-8043: getMaskTransparency() and show() need to return values

---

.gitignore
include/lsst/afw/geom/SpherePoint.h
python/lsst/afw/geom/SpherePoint.i
python/lsst/afw/geom/geomLib.i
src/geom/SpherePoint.cc
tests/testSpherePoint.cc
tests/testSpherePoint.py

`afw::geom::SphPoint` has been implemented as discussed in [DM-5529](https://jira.lsstcorp.org/browse/DM-5529). The one substantial change is the replacement of `offsetTo(SphPoint) -> pair<Angle, Angle>` with `bearingTo(SphPoint) -> Angle`, as discussed previously with @r-owen.
Unit tests are a combination of existing tests for `afw::coord::Coord` and new tests.
Class documentation has been written in the format proposed in [RFC-225](https://jira.lsstcorp.org/browse/RFC-225) for forward-compatibility.

DM-5529: Implement SphPoint

---

python/lsst/afw/display/interface.py

In particular, this means that setDefaultBackend("ds9") will succeed iff
display_ds9 is setup.
N.b. lsst.afw.display.ds9 provides a DisplayImpl that throws when created,
but this allows us to check for a valid display without instantiating it.

Check that the DisplayImpl provides _show()

---

tests/testSpherePoint.py

This change works around a difference in how C++ standard library implementations treat output of NaN to a stream that requires all nonnegative numbers to have a sign. It should allow unit tests to pass on both Linux and MacOS platforms.

DM-8122: SpherePoint tests fail on MacOS

---

include/lsst/afw/table/Schema.h
src/table/Schema.cc
tests/testTableIO.py

Sometimes we want the Schema from a catalog without having to read
the entire catalog (e.g., when setting up for concatenating a bunch
of catalogs). This patch adds two methods to help with that.

table.Schema: allow construction from FITS file

---

python/lsst/afw/table/testUtils.py

This is test support code used to help diagnose DM-8221 that may be useful long-term.

afw/DM-8221: Add test helper for comparing Schemas.

---

include/lsst/afw/image/VisitInfo.h
src/image/VisitInfo.cc
tests/testVisitInfo.py

Adding LST into VisitInfo, by way of a "fake" ERA.

Load LST into VisitInfo tickets/DM-8052

---

include/lsst/afw/table/io/pybind11.h

This file centralizes wrapping of `lsst::afw::table::io::PersistableFacade`. It is designed to be included in the pybind11 `.cc` files of classes that implement `PersistableFacade` using the curiously recurring template pattern.
The function has been successfully tested with local wrappers for `ApCorrMap` and `ChebyshevBoundedField` written as part of DM-7797.

DM-8374: Add function for Pybind11 wrapping of PersistableFacade

---

python/lsst/afw/table/multiMatch.py
tests/testTableMultiMatch.py

- Adds a unit test that's really a smoke test for GroupView. Sample code to replace the source catalogs with something quicker would be welcome.
- Casts catalog indices to `int` to work around the SWIG Python 3 issue. This can be backed out if the SWIG issue described in [DM-8557](https://jira.lsstcorp.org/browse/DM-8557) is fixed.

DM-8557: Test and workaround Python 3 SWIG issue in afw.table.multiMatch.GroupView

---

include/lsst/afw/detection/GaussianPsf.h
include/lsst/afw/detection/Psf.h
src/detection/GaussianPsf.cc
src/detection/Psf.cc
tests/testGaussianPsf.py
tests/testTableArchivesLib.i

which computes the BBox to be returned by computeKernelImage. Pure virtual worker
method doComputeBBox must be implemented by derived classes.

Add computeBBox method to Psf classes

---

python/lsst/afw/math/interpolate.cc

Wrap stringToInterpStyle
Also eliminate use of PTR in the same file and reformat
that bit of code using clang-format.

Wrap math::stringToInterpStyle

---

python/lsst/afw/geom/linearTransform.cc

Wrap `LinearTransform::operator()`
Also update the file as follows:
- Remove commented-out `#include <pybind11/operators.h>`
- Use `namespace lsst {...` in the usual way.
- Wrap `LinearTransform::getParameterVector` (which was commented out)

Wrap LinearTransform::operator()

---

include/lsst/afw/table/pybind11/catalog.h
python/lsst/afw/geom/polygon/polygonLib.py
python/lsst/afw/image/exposure.cc
python/lsst/afw/math/kernel.cc
python/lsst/afw/table/base.cc
python/lsst/afw/table/catalog.py
python/lsst/afw/table/exposure.py
python/lsst/afw/table/sortedCatalog.py

Various issues that occur in packages upstream from `afw`:
- The changes to polygonLib.py are to let `Polygon` be imported without needing other imports first.
- Making `Exposure` a `Persistable` is needed to allow calls to methods that expect a `Persistable`.
- The changes to `kernel.cc` take advantage of the fact that a method with a default argument is equivalent to two methods with no defaults. Using `py::init` is a bit risky, since strictly speaking it's only guaranteed to work if a constructor with a matching signature exists. Using a lambda to make a [custom constructor](http://pybind11.readthedocs.io/en/master/advanced/classes.html#custom-constructors) may be more forward-compatible.

DM-8461: Wrap pipe_tasks with pybind11

---

src/image/makeWcs.cc

Make `makeWcs(metadata, stripMetadata)` reliably strip
metadata (if the `stripMetadata` is true) by stripping
the argument, rather than an internal copy that may be
a deep copy.

Make stripping WCS metadata reliable

---

examples/estimateBackground.py
examples/showCamera.py
examples/simpleStacker.py
examples/spatialCellExample.py
python/lsst/afw/coord/coord.py
python/lsst/afw/geom/ellipses/__init__.py
python/lsst/afw/table/catalogMatches.py
tests/testFunctorKeys.py
tests/testHeavyFootprint.py

These changes fall into 3 categories:
- Fix examples (or in the case of one test, fix what I can and file a ticket to fix the rest)
- Remove obsolete code that was commented out
- Remove a skipped test that will pybind11 compatible.

Fix obsolete uses of cast and vector

---

python/lsst/afw/display/ds9.py

When display_ds9 is not set up the code tries to print the exception. However, in Python 3 the exception no longer exists by the time it is needed, so explicitly bind the exception.
The code is a bit clumsy due to limitations of Python 2, but I include instructions for eventual simplification.
I tried using functools.partial but felt the results were less clear (thought slightly shorter) than the code I adopted.

DM-9433 ds9.py error code not working as intended

---

python/lsst/afw/display/ds9.py

In DM-9504 we saw that storing the original exception thrown when failing to
import ds9 in a closure for the duration of execution causes test failures and
wastes memory. Instead, we generate a new exception which contains only a
minimal error message.

DM-9504: lsst_py3 CI failure due to meas_extensions_ngmix

---

include/lsst/afw/geom/SpherePoint.h
src/geom/SpherePoint.cc
tests/testSpherePoint.py

The first commit in this PR is the fix for [DM-9502](https://jira.lsstcorp.org/browse/DM-9502). The remaining two commits update the overall code for [DM-8713](https://jira.lsstcorp.org/browse/DM-8713) and [DM-7891](https://jira.lsstcorp.org/browse/DM-7891).
Because the DM-8713 update touches nearly every line of C++, reviewing by individual commits rather than using the net diff is strongly recommended.

DM-9502: SpherePoint throws wrong exception for invalid arguments

---

tests/testSpherePoint.cc

Adds a C++-only test for `operator[]`, since it obeys a different spec from `__getitem__` (which is already tested in `testSpherePoint.py`). This PR also adds a `clang-format` pass I missed in DM-9502; because it makes large changes to indentation, it may be useful to review this PR as two separate commits.

DM-8105: Missing test case for SpherePoint

---

include/lsst/afw/geom.h
include/lsst/afw/geom/SpherePoint.h
src/geom/SpherePoint.cc
tests/testSpherePoint.cc

This change lets `SpherePoint` explicitly declare move operations, as proposed in [RFC-209](https://jira.lsstcorp.org/browse/RFC-209), but in a slightly different style than assumed there. This PR also includes some other `SpherePoint` cleanup.

DM-8106: SpherePoint does not have move constructors/assignment

---

python/lsst/afw/geom/ellipses/ellipse.cc
python/lsst/afw/table/aggregates.cc
python/lsst/afw/table/arrays.cc
python/lsst/afw/table/schema.cc

This adds wrappers for two afw methods that are apparently first used in meas_modelfit (lack of test coverage has been noted).

DM-8465: wrap meas_modelfit with pybind11

---

python/lsst/afw/coord/weather.cc
python/lsst/afw/detection/peak.cc
python/lsst/afw/geom/angle/angle.cc
python/lsst/afw/geom/ellipses/conformalShear.cc
python/lsst/afw/geom/ellipses/distortion.cc
python/lsst/afw/geom/ellipses/ellipticityBase.cc
python/lsst/afw/geom/ellipses/radii.cc
python/lsst/afw/geom/ellipses/reducedShear.cc
python/lsst/afw/geom/ellipses/separable.cc
python/lsst/afw/table/schema/schema.cc

This commit adds `__str__` and `__repr__` implementations from the pre-merge `.i` files, with the exception of `SchemaItem.__repr__` (version added during pybind11 cleanup supersedes Swig edition) and `CoordinateBase.*` (difficult to implement and of questionable value). Conforming to RFC-298 is outside the scope of the ticket; these are just the string representations that were previously visible to the stack.

DM-9140: Ensure __str__ and __repr__ copied from Swig

---

python/lsst/afw/table/source/source.cc

SourceFitsFlags values are used as ints so should be wrapped
as individual attributes instead of as an enum.
This proved slightly tricky because module-level enums cannot be
wrapped using `py::cast` or `py::int_` with our version of pybind11:
the code compiles but causes an import error.

DM-9764:  SOURCE_IO_NO_FOOTPRINTS and related enums should be properly wrapped in pybind11

---

include/lsst/afw/geom/Transform.h
python/lsst/afw/geom/endpoint.cc
python/lsst/afw/geom/transform.cc
python/lsst/afw/geom/utils.py
src/geom/Transform.cc
tests/test_endpoint.py
tests/test_transform.py

This PR implements `Transform::getInverse()`, adds a Python-only equality test for `Endpoint`, and updates the style of the Transform code to match the output of `clang-format` (mostly changing whitespace around `&`).

DM-9595: Allow Transform to return its inverse

---

.gitignore
include/lsst/afw/geom/Transform.h
python/lsst/afw/geom/SConscript
python/lsst/afw/geom/transform/__init__.py
python/lsst/afw/geom/transform/transform.cc
python/lsst/afw/geom/transform/transformContinued.py
src/geom/Transform.cc
tests/test_transform.cc
tests/test_transform.py

This commit implements `Transform::getJacobian`. The unit tests in `test_transform.py` were modified slightly to make the test transform non-linear, so that the Jacobian is not constant. A supplementary test was added as `test_transform.cc` to make absolutely sure that the matrix dimensions are what they should be, since conversion to ndarray loses some of that information.

DM-9598: Allow Transform to return a matrix of derivatives

---

src/image/Wcs.cc
tests/testWcsFitsTable.py

The old implementation round-tripped CRVAL through radians because it used Angle, which resulted in a loss of precision and inexactly persisted WCSs.

DM-10105: Avoid loss of precision in Wcs persistence.

---

include/lsst/afw/geom/Transform.h
python/lsst/afw/geom/transform/transform.cc
python/lsst/afw/geom/transform/transformContinued.py
src/geom/Transform.cc
tests/test_transform.cc
tests/test_transform.py

This PR implements `Transform::of` in terms of `ast::prepend`. It deviates slightly from the DM-9599 spec in that the C++ code checks for compatible endpoints at compile time; this turned out to be less work than the original run-time-only design because it reduces the number of overloads that need to be wrapped in pybind11. The need to explicitly consider one overload per endpoint implementation class already complicates things enough.

DM-9599: Support concatenation of Transforms

---

python/lsst/afw/geom/transform/transform.cc
tests/test_transform.py

In Python make sure the FrameSet returned by Transform.getFrameSet
is independent of the contained FrameSet by returning a copy.
Add a test for this.
The C++ API is unchanged because it returns a const FrameSet.
(Python does not respect `const`).

DM-10292: The FrameSet returned by Transform.getFrameSet can change the contained FrameSet in Python

---

include/lsst/afw/table/python/catalog.h
python/lsst/afw/table/base/baseContinued.py
tests/testSimpleTable.py

Helpful in the peak-transferring code needed on the meas_algorithms branch for this issue.

DM-10271: Support deleting slices of a catalog.

---

include/lsst/afw/table/Catalog.h

This is a duplicate of the const_iterator begin, end which formerly
existed.  This const protects the PTR(Record), but not the Record
contents.

Add cbegin, cend routines to Catalog.

---

include/lsst/afw/detection/Footprint.h

Add doxygen documentation to the constructors for the Footprint
object.

Add documentation to Footprints

---

python/lsst/afw/table/exposure/exposure.cc
tests/testExposureTable.py

DM-10289: Make it possible to set empty ValidPolygon on ExposureRecord

---

include/lsst/afw/geom/Endpoint.h
include/lsst/afw/geom/Transform.h
python/lsst/afw/geom/endpoint.cc
python/lsst/afw/geom/python/transform.py
python/lsst/afw/geom/testUtils.py
python/lsst/afw/geom/transform/transform.cc
python/lsst/afw/geom/transform/transformContinued.py
python/lsst/afw/geom/utils.py
src/geom/Endpoint.cc
src/geom/Transform.cc
tests/test_endpoint.py

astshim point data is now in standard AST order:
x0, x1, ...xnPts, y0, y1, ..., ynPts, ...
which is the transposition of the previous order.
Update Transform and Endpoint accordingly.
Drop support for Point3Endpoint because it will require extra code
and we have no immediate use case.

DM-9939: Stop transposing data in Mapping.tranForward and tranInverse

---

include/lsst/afw/image/MaskedImage.h
python/lsst/afw/display/interface.py
python/lsst/afw/image/exposure/exposure.cc
python/lsst/afw/image/exposure/exposureContinued.py
python/lsst/afw/image/image/image.cc
python/lsst/afw/image/maskedImage/maskedImage.cc
tests/testExposure.py
tests/testImage.py
tests/testMask.py
tests/testMaskedImage.py

This adds:
- `array` properties to `ImageBase` (and hence both `Image` and `Mask`).  The setters for these properties delegate to NumPy, so they can accept any value `NumPy` accepts when assigning to an array (including arrays with different types and scalars).
- `image`, `mask`, and `variance` properties for `MaskedImage`.  The setters for these require `Image` and `Mask` objects of the appropriate (so you have to say `.image.array = value` to coerce types or assign scalars).
- `setImage`, `setMask`, and `setVariance` to `MaskedImage`, for consistency with `Exposure.setMaskedImage` and the properties.
- a `maskedImage` property for `Exposure`.  The setter requires a `MaskedImage` of the appropriate type.
- Getters and setters for the image, mask, and variance of `Exposure` that just …

DM-10541: Add properties to image classes

---

python/lsst/afw/display/interface.py
tests/testDisplay.py

Updates to afw.display found in testing display_firefly.
- Fix the __getattr__ method to avoid an infinite recursion in Python 3.
- Reorder tests in testDisplay.py so that displays are not closed prematurely.

DM-10552 Upgrade display_firefly to work with more servers

---

examples/timeWarpExposureUsingTransform.py
include/lsst/afw/geom/Transform.h
include/lsst/afw/math/warpExposure.h
python/lsst/afw/geom/python/transform.py
python/lsst/afw/geom/testUtils.py
python/lsst/afw/geom/transform/transform.cc
src/geom/SkyWcs.cc
src/geom/Transform.cc
src/math/warpExposure.cc
tests/testWarpExposure.py
tests/test_transform.py

Change `Transform::of(first)` to `Transform::then(next)` to improve readability.

DM-10764: Rename Transform::of and Mapping::of to ::then

---

python/lsst/afw/table/schema/schema.cc

To fail to do so results in a deadlock when using python multiprocessing.

DM-10834: pybind: clear error if we're not going to use it

---

src/geom/transformFactory.cc

This commit removes the "do not simplify" flag from `linearizeTransform`, following upstream bug fixes in AST.

DM-10947: Allow linearizeTransform and affineTransform to simplify their mappings

---

examples/wcsTest.cc
python/lsst/afw/display/scaling.cc
src/coord/Coord.cc
src/detection/PsfFormatter.cc
src/formatters/DecoratedImageFormatter.cc
src/formatters/ExposureFormatter.cc
src/formatters/ImageFormatter.cc
src/formatters/KernelFormatter.cc
src/formatters/MaskFormatter.cc
src/formatters/MaskedImageFormatter.cc
src/formatters/PropertyListFormatter.cc
src/formatters/TanWcsFormatter.cc
src/formatters/WcsFormatter.cc
src/image/ImagePca.cc
src/image/VisitInfo.cc
src/math/GaussianProcess.cc
src/math/Interpolate.cc
src/math/LinearCombinationKernel.cc
src/table/io/FitsSchemaInputMapper.cc

This PR eliminates all but one compiler warning (unused `fits::{}::getFormatCode(int8_t)`) when building `afw` with Ubuntu+GCC and MacOS+Clang. Justifications for individual changes are included in the commit messages.
During the MacOS port a few unrelated clang-format changes were made because of the mismatch in clang-format versions between Ubuntu and MacOS. @parejkoj and I allowed them to get committed on the grounds that we will probably standardize on clang-format 5 anyway.

DM-10257: Fix compiler warnings in afw

---

tests/sipterms.cc

Most of the print statements look like they were added when somebody was debugging something, and have been removed on the grounds that they should never have been committed. Several are used to indicate test progress, and have been replaced with logging statements (at `DEBUG` level so they don't pop up in normal runs).
A better solution would be to factor the single monolithic test case into one for each function, but I'm not sure setting up a proper fixture is worth the time in this case.

DM-11237: Cleanup standard output in sipterms.cc.

---

include/lsst/afw/image/Image.h
python/lsst/afw/image/image/image.cc
src/image/Image.cc
tests/test_imageIo1.py

This function provides a bounding box, given the FITS header.

DM-11326: add image::bboxFromMetadata

---

python/lsst/afw/table/base/baseContinued.py
tests/test_astropyTableViews.py

We can't use `columns.get()` on variable-length array fields, so the `unvieewable=copy` mode doesn't work, so we just skip them, unless we should raise. It's hacky, but until they're `get()`able, there's probably not a way around it.

DM-11429 Skip variable-length array fields in asAstropy

---

python/lsst/afw/table/base/baseContinued.py
tests/test_sourceTable.py

Re-merge, after fixing the variable-length arrays problem in DM-11429.

DM-6718 Add str and repr for afw catalog/record

---

src/image/PhotoCalib.cc
tests/test_photoCalib.py

Names used here will have to be updated when RFC-322 is adopted.
This PR is a new one (against master) that supercedes #262.

Implement PhotoCalib ops that output to catalogs.

---

python/lsst/afw/image/slicing.py
tests/test_image.py

That is, when using the syntactic sugar which makes using bboxes easier,
allow an extra argument such as
im[bbox, afwImage.PARENT]
or
im[1000:1010, -1:, afwImage.PARENT]
In the second case we'll use PARENT coordinates when interpreting the
slices (i.e. the "1000" includes x0)

Make it possible to specify an origin (e.g. PARENT) with e.g. im[bbox]

---

python/lsst/afw/coord/utils.py
python/lsst/afw/geom/utils.py
python/lsst/afw/image/basicUtils.py
python/lsst/afw/image/makeVisitInfo.py
python/lsst/afw/image/testUtils.py
tests/test_ampInfoTable.py
tests/test_apCorrMap.py
tests/test_cameraGeom.py
tests/test_chebyshevBoundedField.py
tests/test_coord.py
tests/test_detector.py
tests/test_exposure.py
tests/test_footprint1.py
tests/test_function.py
tests/test_functorKeys.py
tests/test_header.py
tests/test_heavyFootprint.py
tests/test_kernel.py
tests/test_matchFits.py
tests/test_photoCalib.py
tests/test_polygon.py
tests/test_separableXYTransform.py
tests/test_simpleTable.py
tests/test_sourceMatch.py
tests/test_tableIO.py
tests/test_transformBoundedField.py
tests/test_validPolygon.py
tests/test_wcsFitsTable.py

Also fix some deprecation warnings and use of AFW_DIR.

DM-11514: Fix a race condition in tests under pytest-xdist

---

include/lsst/afw/cameraGeom/Detector.h
python/lsst/afw/cameraGeom/cameraConfig.py
python/lsst/afw/cameraGeom/cameraFactory.py
python/lsst/afw/cameraGeom/detector.cc
python/lsst/afw/cameraGeom/testUtils.py
src/cameraGeom/Detector.cc
tests/test_detector.py

Contains coefficients for intra-CCD crosstalk correction.

DM-11268: Detector: add crosstalk matrix

---

python/lsst/afw/table/base/baseContinued.py

Function calls to pybind11-wrapped methods that fail due to bad
argument types can take a very long time to raise an exception,
because the exception message involves stringifying some very big
objects (especially Catalogs).

Don't use try/catch to dispatch catalog overloads.

---

tests/test_maskedImageIO.py
tests/test_methods.py
tests/test_simpleTable.py
tests/test_skyWcs.py
tests/test_wcsFitsTable.py
ups/afw.table

Use `unittest.assertWarns` if available to check that deprecated
asserts raise `DeprecationWarning`. If the version of Python
is too old for unittest to have `assertWarngs` then use a
null context manager instead (and pytest will issue warnings).

DM-12061: Eliminate test warnings in test_methods.py

---

doc/doxygen.conf.in
include/lsst/afw/fitsCompression.h

fitsCompression.cc is causing doxygen warnings:
documented symbol `ImageScale lsst::afw::fits::ImageScalingOptions::determine' was not declared or defined.
This appears to be due to a bug in doxygen (perhaps having to do with
underscores at the end of variable names?). To deal with this, corrected
the grouping markup for ImageScalingOptions::determine and put
fitsCompression.cc on the doxygen exclusion list. This doesn't produce
correct docs (e.g., ImageScalingOptions::determine isn't listed as a
member function) but it's no worse than it was before, more correct and
doesn't produce a warning.

DM-12905: fits: fix doxygen warnings

---

python/lsst/afw/geom/python/transform.py
python/lsst/afw/geom/testUtils.py
python/lsst/afw/math/interpolate.cc
tests/test_interpolate.py

The key functionality was already present (readString, writeString
methods) and just needed to be hooked up to the pickle machinery
and tested.

DM-12025: make Transform pickleable

---

.gitignore
tests/test_transformFactory.py

This PR fixes a bug in `testLinearize` and increases its test coverage, as well as taking care of a few cleanup issues.

DM-12040: Errors in test_transformFactory.py

---

python/lsst/afw/cameraGeom/camera.py
python/lsst/afw/cameraGeom/pupil.py

Adds _centerPupil function and **kwargs to getPupilFactory to
optionally recenter the illuminated portion of a pupil within
a pupil array, similar to what is done in Zemax.

DM-12103: Investigate centering for vignetted pupils

---

tests/test_tableArchives.cc

The wrong variable was being set, leaving the correct one uninitialized.  If the uninitialized memory happened to contain a NaN, it would not compare properly even after round-tripping correctly.

Fix uninitialized variable problem.

---

include/lsst/afw/image/VisitInfo.h
python/lsst/afw/image/visitInfo.cc
src/image/VisitInfo.cc
tests/test_visitInfo.py

Adds a simple function to VisitInfo, that calculates the parallactic angle at the boresight of the exposure.

DM-12473: Add getParallacticAngle() to visitInfo

---

python/lsst/afw/coord/refraction.py
tests/test_refraction.py

Adds a detailed calculation of refraction to `afw.coord` that can account for local atmospheric conditions in `Weather`.
Needed for generating Differential Chromatic Refraction-corrected template images.

DM-13096: Add refraction calculation

---

include/lsst/afw/fits.h
include/lsst/afw/fitsDefaults.h
include/lsst/afw/image/Image.h
include/lsst/afw/image/Mask.h
include/lsst/afw/image/Utils.h
include/lsst/afw/table/Catalog.h
include/lsst/afw/table/Exposure.h
include/lsst/afw/table/Schema.h
include/lsst/afw/table/SortedCatalog.h
include/lsst/afw/table/io/Persistable.h
include/lsst/afw/table/io/python.h
include/lsst/afw/table/python/catalog.h
include/lsst/afw/table/python/sortedCatalog.h
python/lsst/afw/fits/fits.cc
python/lsst/afw/image/image/image.cc
python/lsst/afw/image/mask/mask.cc
python/lsst/afw/image/readMetadata.cc
python/lsst/afw/math/backgroundList.py
python/lsst/afw/table/exposure/exposure.cc
python/lsst/afw/table/schema/schema.cc
src/fits.cc
src/formatters/TanWcsFormatter.cc
src/formatters/WcsFormatter.cc
src/image/MaskedImage.cc
tests/ramFitsIO.cc
tests/test_spanSets.cc
tests/test_tableArchives.cc
tests/test_ticket2352.py

We have used INT_MIN to indicate that the first non-empty HDU should
be selected, but never exported the symbol to python. Changed the name
(but kept the value) so it's clear what it is, and exported it to
python.

DM-13110: export magic value to select default HDU

---

.gitignore
include/lsst/afw/geom/Endpoint.h
python/lsst/afw/geom/endpoint.cc
src/geom/Endpoint.cc
tests/test_endpoint.cc

The C++ operator only handles Endpoints with the same `BaseEndpoint` parent (a more general operator is hard to implement because of how templates and inheritance interact, and would not be useful in C++ anyway). The Pybind11 wrapper uses conditional templates to provide a universal comparison operator for the Python API.

DM-10819: Define Endpoint equality

---

include/lsst/afw/math/Random.h
src/math/Random.cc

Random has accepted a seed value of zero and then thrown an exception.
This is not necessary, since we can construct a seed value that is
non-zero from whatever we're given.

DM-12995/RFC-436: Random: ensure seed is non-zero

---

include/lsst/afw/geom/Box.h
include/lsst/afw/table/Exposure.h
include/lsst/afw/table/aggregates.h
python/lsst/afw/table/aggregates/aggregates.cc
python/lsst/afw/table/aggregates/aggregatesContinued.py
src/math/ChebyshevBoundedField.cc
src/math/TransformBoundedField.cc
src/table/Exposure.cc
src/table/aggregates.cc
tests/test_functorKeys.py

This adds `FunctorKeys` for `Box2I` and `Box2D`, which should start us towards recording boxes in tables in a consistent way.
I've also updated three other classes in afw to use the new `FunctorKey` because they were already using the same convention and hence the change could be done in a backwards-compatible way.  Two others (`AmpInfoRecord` and `Chebyshev1Function2d`) use a different convention and cannot be converted without changing APIs and/or persistence formats.

DM-13189: add FunctorKey for Boxes

---

include/lsst/afw/math/Stack.h
python/lsst/afw/math/stack.cc
src/math/Stack.cc
tests/test_stacker.py

Changes here were done to in a way that should guarantee ABI compatibility with w_2018_04 (when the fixed version of that comes out); I didn't want anyone working on coadds this week to have to rebuild everything (instead they'll just have to rebuild afw).  Note that this precludes some cleanups I'd have otherwise tried to do in nearby code (wow, `statisticsStack` is a mess!).

DM-13396: Add more flexible mask propagation to statisticsStack.

---

python/lsst/afw/cameraGeom/utils.py

This allows the 'imageSource' to throw an exception rather than returning
a nonsense input.

DM-13437: makeImageFromCamera: catch exceptions from retrieving image

---

python/lsst/afw/cameraGeom/cameraPoint.cc
python/lsst/afw/cameraGeom/cameraSys.cc
python/lsst/afw/coord/weather.cc
python/lsst/afw/detection/peak.cc
python/lsst/afw/geom/angle/angle.cc
python/lsst/afw/geom/endpoint.cc
python/lsst/afw/geom/spherePoint/spherePoint.cc
python/lsst/afw/image/photoCalib.cc
python/lsst/afw/image/visitInfo.cc
python/lsst/afw/math/boundedField.cc
python/lsst/afw/table/schema/schema.cc

This PR replaces trivial pybind11 wrappers of operator<< with calls to `wrapOutputOp`, which is introduced in lsst/utils#47. Non-trivial wrappers (typically ones that add extra information to `__repr__`) are left untouched.

DM-10066: Provide utility function for wrapping operator<<

---

src/fits.cc
tests/test_fits.py

There are some keywords that, if we write, it will corrupt the
FITS file because cfitsio takes care of them; these typically
have to do with core FITS concepts (size, column definitions,
compression) that we handle explicitly through cfitsio
interfaces. And the user shouldn't care about them either.
However, there are some keywords that need to leak through
our keyword stripping because afw::table::io needs to see
them in order to build a Schema; we just won't allow those
to be written.
This includes refactoring the 'isKeyIgnored' function to make
the list of keywords more easily extensible.

DM-13511: fits: extend list of header keywords to ignore

---

tests/test_skyWcs.py

The test of SkyWcs.getTanWcs was only passing because TAN-SIP
was not being written out by AST, a problem fixed on this ticket.
For now remove the test for SkyWcs.getTanWcs();
tickets/DM-10765 has a much better test, but it relies on
a function that that is not available on master.

DM-13539: astshim fails to preserve SIP terms for some TAN SIP when writing FITS metadata

---

doc/imageAlgorithm.dox
include/lsst/afw/image/ImageAlgorithm.h
include/lsst/afw/math/Function.h
src/math/Spline.cc

Minor changes required for AFW:
* Boost 1.65.1 no longer provides `std::tr1::function`; cut over to `std::function`
* Explicit `#include <cmath>` required to get `std::sqrt` for Function.h on OSX
Passed Jenkins CI here: https://ci.lsst.codes/blue/organizations/jenkins/stack-os-matrix/detail/stack-os-matrix/27178/pipeline

DM-12521: Update boost to 1.66

---

include/lsst/afw/table/python/catalog.h
python/lsst/afw/table/baseColumnView/baseColumnView.cc

pybind11's own numpy APIs are now preferred, as that's what the ndarray pybind11 converters use.

DM-13534: avoid usage of old ndarray PyConverter APIs

---

python/lsst/afw/cameraGeom/fitsUtils.py

This looks like the right thing to do and fixes a very verbose
set of warnings in test_camGeomFitsUtils.py

DM-13129: Warnings in test_camGeomFitsUtils.py

---

include/lsst/afw/table/BaseRecord.h
python/lsst/afw/table/base/base.cc
python/lsst/afw/table/base/baseContinued.py
src/table/BaseRecord.cc

Old implementation was very inefficient, even in Python, but we can make it even faster by moving it to C++.

DM-13750: Move BaseRecord.__str__ implementation to C++.

---

include/lsst/afw/math/ConvolveImage.h
include/lsst/afw/math/Random.h
include/lsst/afw/math/detail/Convolve.h
include/lsst/afw/math/warpExposure.h
src/geom/Transform.cc
src/image/TransmissionCurve.cc
src/math/Interpolate.cc
src/math/Random.cc

This PR removes all mention of `pex::exceptions::MemoryError` from `afw`, modifying code to throw `std::bad_alloc` instead.
This change removes error messages from the emitted exception, but there's a good chance that trying to allocate the strings for those would have triggered `bad_alloc` anyway.

DM-13655: Phase out MemoryError and TimeoutError from pex::exceptions

---

include/lsst/afw/geom/Transform.h
src/geom/Transform.cc

Much of the runtime performance degradation from SkyWcs appears to be
due to AST rebuilding the transformation every time we want to use it.
By calculating and caching the '_frameSet->getMapping' at construction
time, and using that for the coordinate transformations, we can cut
the corner and save a LOT of time.
Thanks to Russell Owen for the idea.

DM-13847: Transform: calculate Mapping at construction time

---

include/lsst/afw/detection/Psf.h
include/lsst/afw/geom/Point.h
python/lsst/afw/detection/psf.cc
src/detection/Psf.cc
src/geom/Point.cc

Larger cache makes things go faster.

DM-13854: extend cache in Psf

---

src/table/Match.cc
tests/test_sourceMatch.py

The formula used for converting unit sphere distance^2 to an Angle
isn't precise for small distance. Using an alternative formula that
(unfortunately) includes a sqrt is more precise.
Bug identified by Dominique Boutigny.

DM-13891: matchRaDec: fix imprecision at small distance

---

src/geom/SpherePoint.cc

by initializing the fields in the correct order.

DM-13884: SpherePoint() initializes fields in the wrong order (compiler warning)

---

include/lsst/afw/image/Filter.h
python/lsst/afw/image/filter.cc
python/lsst/afw/image/utils.py
src/image/Filter.cc
tests/test_color.py

This adds additional FilterProperties `lambdaMin` and `lambdaMax`, and should work in a backwards-compatible way. But, I am not confident working with C++, so I would appreciate an extra-careful look at my changes to make sure I haven't messed something up.

tickets/DM-13834: Add minimum and maximum wavelength to FilterProperty.

---

python/lsst/afw/coord/refraction.py

Also fix return value docstring.

DM-14548: Make dimensionless quantities in `refraction` `floats`

---

include/lsst/afw/image/Exposure.h
python/lsst/afw/image/exposure/exposure.cc
src/image/Exposure.cc
tests/test_exposure.py

This PR adds a method, `Exposure::getCutout`, that returns a fixed-sized image centered on particular sky coordinates. To ensure the image always has the desired size, empty pixels (for coordinates near the edge of an exposure) are allowed.
Note that this implementation does not use the `Box2D` -> `Box2I` conversion suggested by @TallJimbo. That conversion prioritizes keeping particular pixels over keeping the desired size, and correctly clipping the `Box2I` back to the desired size would require complex conditions on the sky coordinates' location within a pixel.

DM-14072: Add getCutout method to Exposure

---

tests/test_fitsTables.cc
tests/test_footprint.py
tests/test_propertyListPersistence.py

Without this you can't run `pytest $AFW_DIR` and expect it to work.

DM-14844: Look up data files relative to known locations

---

.gitignore
src/image/Exposure.cc

This PR modifies the implementation of `Exposure::getCutout` to use the `Box2I::makeCenteredBox` factory introduced by lsst/geom#4. However, as a side effect the `getCutout` method became considerably more complex (17 LLOC for input validation plus three logical processing steps); any suggestions on how to break it up would be appreciated.

DM-14690: Add ability to construct centered boxes

---

python/lsst/afw/display/interface.py

This PR is a very small bug fix for `afwDisplay.setDefaultMaskTransparency` to swap the order of arguments when these are a dictionary, that are provided to `setMaskTransparency`.

DM-14840 Make mask transparency and color "sticky" in display_firefly

---

include/lsst/afw/image/Exposure.h
include/lsst/afw/math/ConvolveImage.h
src/image/Exposure.cc
tests/test_exposure.py

This PR changes the behavior of `Exposure::getCutout` when creating cutouts that extend off the edge of the original exposure. Previously, the off-edge pixels were left blank; the new behavior is to set them to `math::edgePixel`. Note that this means `getCutout` now throws an exception if the `NO_DATA` flag has been deleted from the global mask plane dictionary.

DM-14814: Change invalid pixel handling by Exposure::getCutout

---

include/lsst/afw/geom/SipApproximation.h
python/lsst/afw/geom/SConscript
python/lsst/afw/geom/__init__.py
python/lsst/afw/geom/sipApproximation.cc
src/geom/SipApproximation.cc
tests/test_sipApproximation.py

Best to start with the docs for the afw/geom/SipApproximation class and the afw/math/polynomials namespace (in afw/math/polynomials.h) to get the big picture.

DM-13065: SipApproximation

---

python/lsst/afw/image/calib.cc

Put the `PropertySet` in front of `list[Calib]` since `PropertySet` now has` __len__` and `__getitem__` methods and so pybind11 thinks that it is probably a sequence.

Change order of constructors for lsst.afw.image.Calib

---

python/lsst/afw/image/slicing.py
python/lsst/afw/table/match/matchContinued.py

Ignore some lines with `noqa N807` where it makes sense (support for new pep8_naming)

Skip N807 in flake8/pep8 naming

---

include/lsst/afw/image/PhotoCalib.h
tests/test_photoCalib.py

Jointcal was producing negative mean calibrations, which we should not allow. I'm going to fix jointcal, but we should also trap for them here.

DM-16235: Raise if mean or error are negative

---

tests/test_image.py
tests/test_mask.py
tests/test_maskedImage.py

Previously, we were checking against hard-coded “guesses” of what NumPy might
return for a given array. That conflates two different tests:
- Are we correctly delegating formatting to NumPy?
- Is NumPy actually giving us what we want?
This modification means we are only testing the former, which, I suggest, is
appropriate. We could consider adding a test to verify that some future
version of NumPy doesn't change its output to something which is unhelpful to
us, but I suggest that that is out of scope for this work.

DM-16291: Use NumPy stringification to generate test results.

---

include/lsst/afw/geom/detail/frameSetUtils.h
src/fits.cc
src/geom/detail/frameSetUtils.cc
tests/test_makeLimitedFitsHeader.py

In FITS a "0" is an integer so we must ensure that "0.0" becomes a floating point number when written as a FITS header card. This PR also includes some improvements to the tests and a fix to booleans.

DM-16386: Update makeLimitedFitsHeader to force floats to correct type

---

doc/lsst.afw.display/index.rst
python/lsst/afw/display/ds9.py
python/lsst/afw/display/ds9Regions.py
python/lsst/afw/display/interface.py
python/lsst/afw/display/rgb/rgbContinued.py
python/lsst/afw/display/utils.py
python/lsst/afw/display/virtualDevice.py

This PR converts all docstrings in `lsst.afw.display` to numpydoc format. It makes no attempt to fill in types, descriptions, etc. that cannot be easily inferred from adjacent code.

DM-16858: Convert afw.display to numpydoc

---

doc/lsst.afw.coord/index.rst
python/lsst/afw/coord/__init__.py
python/lsst/afw/coord/refraction.py

This PR adds the Python code in `lsst.afw.coord` to the documentation build, and rearranges the documentation to conform to current guidelines.

DM-16856: Convert afw.coord to numpydoc

---

doc/lsst.afw.formatters/index.rst
python/lsst/afw/formatters/__init__.py

There are no docstrings to convert on this ticket, so I just added the subpackage to the build and confirmed that the pybind11 functions show up.

DM-16860: Enable lsst.afw.formatters documentation.

---

python/lsst/afw/table/multiMatch.py

Fixes a warning from Python 3.7

DM-17088: Replace collections.Mapping with collections.abc.Mapping

---

include/lsst/afw/table/IdFactory.h
python/lsst/afw/table/idFactory.cc

This encapsulates the number of (usable) bits in a record ID in order to avoid having "64" or "63" magic numbers strewn about downstream code.

Add helper method for IdFactory.

---

doc/lsst.afw.fits/index.rst
python/lsst/afw/fits/compression.py
python/lsst/afw/fits/pickleFits.py
tests/test_imageIo1.py

This PR ensures all public Python functions in `lsst.afw.fits` conform to the style guide, and adds some stub documentation (I couldn't find anything about `lsst::afw::fits` in the Doxygen docs). It also fixes an unintended side effect in one of the documented functions.

DM-16859: Convert afw.fits to numpydoc

---

src/detection/FootprintMerge.cc
tests/test_footprintMergeCatalog.py

that overlaps previously disconnected higher priority footprints.
Include unit test that simulates this case.

DM-17431: Respect priority order when merging a footprint

---

src/fits.cc
tests/test_fits.py

Sogo Mineo has pointed out that afw can write a ZQUANTIZ header
keyword (e.g., it is picked up when we read a compressed FITS
header we wrote, and then that header is transferred to a new
file), which can break ds9's handling of mask extensions.
ZQUANTIZ is related to how FITS tile compression is done, and
so we should never read or write it (we leave it up to cfitsio).

DM-19300: fits: ignore ZQUANTIZ keyword

---

python/lsst/afw/geom/angle/__init__.py
python/lsst/afw/geom/angle/angle.py
python/lsst/afw/geom/coordinates/__init__.py
python/lsst/afw/geom/coordinates/coordinates.py
python/lsst/afw/geom/spherePoint/__init__.py
python/lsst/afw/geom/spherePoint/spherePoint.py

This PR removes a number of aliases to `lsst.geom` that were causing problems . According to their comments, the aliases were used to support unpickling of old `lsst.afw.geom` objects; the separate aliases that let code refer to `lsst.geom` members as if they were in `lsst.afw.geom` has not been touched.

DM-19366: afw unit tests do not run on some platforms

---

include/lsst/afw/image/PhotoCalib.h
python/lsst/afw/image/photoCalib.cc
src/image/PhotoCalib.cc
tests/test_photoCalib.py

Also vectorize catalog array operations for a big speedup on AST-backed BoundedFields.

DM-10155: Implement in-place SourceCatalog operators in PhotoCalib

---

.gitignore
doc/index.rst
doc/lsst.afw.typehandling/index.rst
include/lsst/afw/typehandling/GenericMap.h
include/lsst/afw/typehandling/PolymorphicValue.h
include/lsst/afw/typehandling/SimpleGenericMap.h
include/lsst/afw/typehandling/Storable.h
include/lsst/afw/typehandling/python.h
include/lsst/afw/typehandling/test.h
python/lsst/afw/typehandling/SConscript
python/lsst/afw/typehandling/_GenericMap.cc
python/lsst/afw/typehandling/_GenericMap.py
python/lsst/afw/typehandling/_SimpleGenericMap.cc
python/lsst/afw/typehandling/_SimpleGenericMap.py
python/lsst/afw/typehandling/_Storable.cc
python/lsst/afw/typehandling/__init__.py
python/lsst/afw/typehandling/_typehandling.cc
python/lsst/afw/typehandling/testUtils.py
src/typehandling/PolymorphicValue.cc
src/typehandling/python.cc
tests/test_Storable.py
tests/test_genericmap.cc
tests/test_polymorphicValue.cc
tests/test_simpleGenericMap.cc
tests/test_simpleGenericMap.py
tests/test_storable.cc

This pull request creates a new subpackage, `lsst.afw.typehandling`, containing the `Storable` and `HeteroMap` interfaces. A single reference implementation of `HeteroMap`, `SimpleHeteroMap`, is provided as well. `HeteroMap` is expected to be used to simplify the persistence of complex compound types such as `ExposureInfo`.
`(Mutable)HeteroMap` has all the capabilities of a Python `(Mutable)Mapping`, aside from some restrictions on key and value types. The C++ class is more limited; in particular, until [DM-19467](https://jira.lsstcorp.org/browse/DM-19467) there is no way to iterate over or persist a `HeteroMap` in C++.

DM-17981: Create type-safe heterogenous map

---

python/lsst/afw/math/warper.py

Adds a note to `warpExposure` to point out that the PSF is not warped.

tickets/DM-19660: update warpExposure documentation

---

src/coord/Observatory.cc

The Observatory latitude and longitude appear to have been switched in the string representation.

DM-19902: Observatory longitude should be W and latitude N.

---

COPYRIGHT
include/lsst/afw/cameraGeom/Detector.h
include/lsst/afw/detection/Psf.h
include/lsst/afw/geom/SkyWcs.h
include/lsst/afw/geom/polygon/Polygon.h
include/lsst/afw/image/ApCorrMap.h
include/lsst/afw/image/CoaddInputs.h
include/lsst/afw/image/Filter.h
include/lsst/afw/image/PhotoCalib.h
include/lsst/afw/image/TransmissionCurve.h
include/lsst/afw/image/VisitInfo.h
include/lsst/afw/typehandling/PolymorphicValue.h
include/lsst/afw/typehandling/Storable.h
include/lsst/afw/typehandling/test.h
python/lsst/afw/typehandling/_Storable.cc
src/geom/SkyWcs.cc
src/geom/polygon/Polygon.cc
src/image/ApCorrMap.cc
src/image/CoaddInputs.cc
src/image/Filter.cc
src/image/PhotoCalib.cc
src/image/VisitInfo.cc
src/typehandling/PolymorphicValue.cc
src/typehandling/Storable.cc
tests/test_Storable.py
tests/test_readers.py
tests/test_storable.cc
tests/test_warpExposure.py
tests/test_warper.py

This PR adds the `Storable` mixin to all `afw` classes in `ExposureInfo` (note that it does not modify `daf::base::PropertySet`, which as noted on [Jira](https://jira.lsstcorp.org/browse/DM-19575) will need special treatment for now). This amounts to adding the following four methods, though some keep their default implementation of throwing an `UnsupportedOperationException`:
* `cloneStorable`: creates a `shared_ptr<Storable>`; implemented in terms of a more specific `clone` if applicable. Using a virtual `cloneStorable` instead of shadowing (as was done with e.g. `BaseTable`) is less prone to developer error, because only one implementation is required (e.g., in `Psf`) rather than one for every subclass.
* `equals`: compares the object to any `Storable`, usually returning `false` for …

DM-19575: Add Storable mixin to ExposureInfo components

---

include/lsst/afw/typehandling/GenericMap.h
include/lsst/afw/typehandling/PolymorphicValue.h
include/lsst/afw/typehandling/SimpleGenericMap.h
include/lsst/afw/typehandling/test.h
python/lsst/afw/typehandling/_GenericMap.cc
python/lsst/afw/typehandling/_GenericMap.py
src/typehandling/PolymorphicValue.cc
tests/test_simpleGenericMap.cc

This PR introduces the visitor/"iteration" mechanism originally planned for `GenericMap`, adds some iteration-related features to `GenericMap` and `SimpleGenericMap`, and performs some refactoring of the code added in #461 that should make `GenericMap` easier to use and maintain. Because there are a lot of changes, I recommend reading the PR commit by commit (and possibly skipping the two "refactor" commits entirely, as they involve pushing a lot of TMP into private code).
One design decision that I'd like feedback on involves changing `GenericMap::keys` from a snapshot to a view. There needs to be _some_ API that lets `GenericMap` know how to iterate over its implementation class, and it's best if that API is non-throwing. I see three solutions that satisfy this requirement:
1. Make …

DM-19467: Add C++ iteration to GenericMap

---

doc/lsst.afw.typehandling/index.rst
python/lsst/afw/typehandling/_GenericMap.py
python/lsst/afw/typehandling/_SimpleGenericMap.py
python/lsst/afw/typehandling/__init__.py
python/lsst/afw/typehandling/testUtils.py
tests/test_simpleGenericMap.py

This PR adds non-templated interfaces to `GenericMapS`, `MutableGenericMapS`, and `SimpleGenericMapS`. These interfaces should make `GenericMap` more `dict`-like for most Python users.

DM-19556: Use TemplateMeta with GenericMap

---

doc/manifest.yaml

This PR adds `lsst.afw.typehandling` to the site-wide documentation build; this subpackage was accidentally omitted in #461.

DM-20142: Write DMTN on Exposure and persistence work

---

doc/lsst.afw.table/index.rst

This PR solves a documentation [build error](https://ci.lsst.codes/blue/organizations/jenkins/sqre%2Finfra%2Fdocumenteer/detail/documenteer/554/pipeline) on Jenkins:
```
File "/j/ws/sqre/infra/documenteer/doc_template/home/.local/lib/python3.7/site-packages/sphinx/environment/__init__.py", line 785, in get_doctree
with open(doctree_filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/j/ws/sqre/infra/documenteer/doc_template/_build/doctree/py-api/lsst.afw.table.multiMatch.CoordKey.doctree'
The full traceback has been saved in /tmp/sphinx-err-zna3ruxo.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at …
```

DM-20659: Fixes for the lsst.afw.table doc build

---

doc/lsst.afw.image/exposure-fits-metadata.rst
include/lsst/afw/image/Exposure.h
include/lsst/afw/image/ExposureFitsReader.h
include/lsst/afw/image/ExposureInfo.h
include/lsst/afw/typehandling/GenericMap.h
include/lsst/afw/typehandling/test.h
python/lsst/afw/cameraGeom/detector/detector.cc
python/lsst/afw/detection/_psf.cc
python/lsst/afw/geom/polygon/polygon.cc
python/lsst/afw/geom/skyWcs/skyWcs.cc
python/lsst/afw/image/apCorrMap/apCorrMap.cc
python/lsst/afw/image/coaddInputs.cc
python/lsst/afw/image/exposureInfo.cc
python/lsst/afw/image/filter.cc
python/lsst/afw/image/photoCalib.cc
python/lsst/afw/image/transmissionCurve.cc
python/lsst/afw/image/visitInfo.cc
python/lsst/afw/table/_aggregates.cc
python/lsst/afw/table/_exposure.cc
python/lsst/afw/table/_slots.cc
python/lsst/afw/table/_source.cc
python/lsst/afw/table/io/_persistable.cc
src/image/ExposureFitsReader.cc
src/image/ExposureInfo.cc
src/image/Filter.cc
tests/testTableArchivesLib.cc
tests/test_exposure.py
tests/test_exposureTable.py
tests/test_multiband.py
tests/test_simpleGenericMap.cc

This PR changes the implementation of `ExposureInfo` to store components in a `GenericMap` rather than in dedicated pointers, and provides a generic API to add and remove components. The `filter`, `metadata`, and `visitInfo` components have not been migrated, because `metadata` cannot be made compatible with `GenericMap` due to package dependencies, `filter` cannot be round-tripped through `table::io` persistence, and both `filter` and `visitInfo` have a custom persisted form that would be broken by migration.
I'm a bit concerned about the API introduced in 8dcab8b23ab28486d1938f6b570b50c825f981fb. Not only does it expose the `GenericMap` back-end (which may be inevitable, given the requirements for this epic), but it's also fairly complex:
- setComponent(Key, shared_ptr<? extends …

DM-17982: Reiplement ExposureInfo using GenericMap

---

include/lsst/afw/image/PhotoCalib.h
python/lsst/afw/image/photoCalib.cc
tests/test_photoCalib.py

Add localCalib unittest.
Fix flux names in local calib tests.
Add getLocalCalibration function to header.
Add pybindings.
Add test comment.
Remove superfluous test.
Debug getLocalCalibration
clang-format of .h file

DM-21181: Add getLocalCalibration function to photoCalib.

---

include/lsst/afw/typehandling/GenericMap.h
include/lsst/afw/typehandling/python.h
include/lsst/afw/typehandling/test.h
python/lsst/afw/typehandling/_GenericMap.cc
tests/SConscript
tests/testGenericMapLib.cc
tests/test_Storable.py
tests/test_simpleGenericMap.py

This PR adds unit tests to `GenericMap` that pass objects from Python to C++ and/or vice versa. This exposes behavior that was not adequately tested with previous tests.
Bugs fixed:
- Building `afw` with Scons no longer issues an "ignoring a non-existent file" warning
- `GenericMap`'s policy on type conversions is now explicitly described in the API docs
- Python builtin integers are no longer demoted to `int`, nor Python floats to `float`, when inserted into a `GenericMap` (but see DM-21268, below)
- `Storable` values (i.e., non-pointers) can now be retrieved from a `GenericMap` in Python
- Storage and retrieval of integers in C++ now work consistently across platforms
Bugs deferred:
- `GenericMap`'s weakly-typed `insert` method turns C-strings into `bool` …

DM-19582: Add cross-language GenericMap unit tests

---

src/fits.cc
src/geom/detail/frameSetUtils.cc
tests/test_frameSetUtils.py
tests/test_makeLimitedFitsHeader.py

The FITS standard doesn't allow NaN as a value. NaNs turning up in a PropertyList can confuse things so this change traps this and either drops the entire item or replaces with FITS undefined value.

DM-21355: Try to prevent NaN values turning up in FITS headers

---

.gitignore
include/lsst/afw/image/ExposureInfo.h
include/lsst/afw/image/detail/StorableMap.h
include/lsst/afw/typehandling/GenericMap.h
include/lsst/afw/typehandling/Key.h
include/lsst/afw/typehandling/detail/type_traits.h
src/image/ExposureInfo.cc
src/image/detail/StorableMap.cc
tests/test_exposure.py
tests/test_genericmapkey.cc
tests/test_storablemap.cc

This PR creates a simplified version of `afw::typehandling::GenericMap` called `afw::image::detail::StorableMap`, which does not try to provide any compile-time heterogeneity but keeps an API based on `afw::typehandling::Key`. It then replaces the use of `GenericMap` inside `ExposureInfo`.

DM-21327: Replace ExposureInfo implementation with homogeneous map

---

examples/convolveLinear.cc
examples/decoratedImage.cc
examples/mask.cc
examples/maskedImageFitsIo.cc
examples/simpleConvolve.cc
examples/spatiallyVaryingConvolve.cc
examples/timeConvolve.cc
examples/timeWcs.cc
examples/wcsTest.cc
include/lsst/afw/typehandling/Storable.h
include/lsst/afw/typehandling/python.h
python/lsst/afw/typehandling/_Storable.cc
src/geom/SpanSet.cc
src/geom/detail/frameSetUtils.cc
src/image/ExposureFitsReader.cc
src/image/ExposureInfo.cc
src/image/MaskedImageFitsReader.cc
src/image/PhotoCalib.cc
src/math/warpExposure.cc
tests/background.cc
tests/maskedImage1.cc
tests/ramFitsIO.cc
tests/statistics.cc
tests/testGenericMapLib.cc
tests/test_Storable.py

This PR fixes a bug that prevented `Storable` objects from being usable unless they were continuously referenced by Python code. The fix depends on lsst/utils#75.
It also implements and tests cloning of Python `Storable`s, which was left unsupported due to an oversight.

DM-21314: Investigate GC problems with Storable

---

python/lsst/afw/geom/__init__.py

This PR prevents arbitrary `lsst.geom` classes from being imported into `lsst.afw.geom`. The import broke the pipelines docs when classes did not have `afw.geom` counterparts.

DM-22209: Fix pipelines_lsst_io bug from d_2019_11_06

---

src/table/Exposure.cc
tests/test_exposureTable.py

Also add a persistence test to confirm metadata is round-tripped.

DM-22260: Add metadata to temporary catalog to be persisted.

---

include/lsst/afw/cameraGeom/Amplifier.h
python/lsst/afw/cameraGeom/amplifier/amplifier.cc
tests/test_amplifier.py

Amplifier BBoxes for prescan and overscan regions are elsewhere inconsistently
named serial/parallel vs horizontal/vertical. To ensure these are used
consistently, add methods to allow both conventions to work correctly.
Add unit tests to check the consistency of these methods.

DM-21276: Add prescan/overscan bbox get/set alias methods.

---

python/lsst/afw/fits/fits.cc

This pybind11 addition makes parsing multi-HDU DECam files much faster.

DM-22708: Fix decam gen3 ingest

---

doc/iteratorsAndLocators.dox

Adapting to minor edits made to the example code file.

DM-7584: Fix missing code examples.

---

include/lsst/afw/geom/ellipses/GridTransform.h
include/lsst/afw/image/ImageBase.h
include/lsst/afw/image/MaskedImage.h
include/lsst/afw/image/Utils.h
include/lsst/afw/math/Background.h
include/lsst/afw/math/ConvolveImage.h
include/lsst/afw/math/Kernel.h
include/lsst/afw/table/Match.h
include/lsst/afw/table/Source.h
include/lsst/afw/table/io/python.h

DM-22276 was closed as a duplicate of DM-22814. This commit updates comments
referring to the former to point to the latter so that they are easier to find
in future.

Update tickets associated with deprecations.

---

include/lsst/afw/math/ConvolveImage.h
include/lsst/afw/math/detail/Convolve.h
src/math/ConvolveImage.cc
src/math/Kernel.cc
src/math/detail/BasicConvolve.cc
src/math/offsetImage.cc
src/math/warpExposure.cc
tests/test_tableArchives.cc

This PR replaces calls to `Kernel.getCtrX` and `getCtrY` with `getCtr`, and calls to `setCtrX` and `setCtrY` with `setCtr`.

DM-23651: ap_pipe calls some deprecated things

---

src/fits.cc
tests/test_exposure.py

When reading from fits files from cfitsio>=3.38, cfitsio capitalizes keywords in some scenarios but not all. This PR normalizes capitalization when reading in all of those cases and warns the user this action has happened.
When writing to fits files, cfitsio>=3.38 will capitalize all keywords, including long ones. This PR will warn the user that this will be happening.

capitalize on read and warn, warn when keywords are capitalized on write for fits files

---

examples/imageBackground.cc
include/lsst/afw/math/Background.h
python/lsst/afw/math/background/backgroundContinued.py
python/lsst/afw/math/backgroundList.py
tests/background.cc
tests/test_background.py

The PR reverts the portions of #505 that relate to `Background`, then removes all mention of deprecation from the corresponding documentation.

DM-24565: Un-deprecate old APIs related to afw.math.Background

---

src/fits.cc

When reading a fits keyword, we log only debug messages due to
proliferation of old files.

Drop WARN to DEBUG on uppercasing keywords on read

---

include/lsst/afw/table/python/catalog.h
python/lsst/afw/table/_base.py
tests/test_simpleTable.py

This only works when the key is a `str` name or a `Key` instance; because support for slice assignment for all other fields currently delegates so much to NumPy, it's a lot harder to make that work for Flags.

DM-6981: Implement assignment to Flag columns in the pybind11 layer.

---

python/lsst/afw/table/multiMatch.py

This was necessary under SWIG, but not under pybind11.

DM-8591: Follow-up pybind11 behavior with numpy.int64s as indices in Python 3

---

src/math/Stack.cc

Jenkins run [#32492](https://ci.lsst.codes/blue/organizations/jenkins/stack-os-matrix/detail/stack-os-matrix/32492/pipeline).
[Jira ticket](https://jira.lsstcorp.org/browse/DM-25253).
Paircoded with @arunkannawadi!

DM-25253: Warn when weights are ignored in statisticsStack

---

python/lsst/afw/math/backgroundList.py

Starting in Sphinx 3 the extra `()` will become a Sphinx build failure.

DM-26826: Fix See Also section in BackgroundList

---

.gitignore
include/lsst/afw/image/FilterLabel.h
python/lsst/afw/image/SConscript
python/lsst/afw/image/__init__.py
python/lsst/afw/image/filterLabel.cc
src/image/FilterLabel.cc
tests/test_filterLabel.cc
tests/test_filterLabel.py

This PR implements the `FilterLabel` class and unit-tests its functionality. Integration with `Exposure` is not yet supported, and will be added later.

DM-21333: Implement afw.image.Filter replacement(s)

---

python/lsst/afw/geom/wcsUtils/wcsUtilsContinued.py
tests/test_wcsUtils.py

This PR removes the function `makeDistortedTanWcs` and merges its unit tests with those of `computePixelToDistortedPixel`.

DM-22114: Remove deprecated `makeDistortedTanWcs`

---

tests/test_skyWcs.py

This fixes insignificant changes we've seen in ast 9.2.3 in the cd matrix.

Increase atol and rtol when comparing cdmatrix for wcs

---

doc/imageAlgorithm.dox
doc/iteratorsAndLocators.dox
doc/mainpage.dox

This PR updates all Doxygen links of the form `\link target \endlink` to have whitespace on both sides of the target; the previous format wasn't properly tokenized by Doxygen 1.8.18.

DM-27246: Lots of Doxygen warnings in afw

---

include/lsst/afw/image/Exposure.h
include/lsst/afw/image/ExposureInfo.h
src/image/ExposureFitsReader.cc
src/image/ExposureInfo.cc
tests/test_exposure.py

This PR enforces the convention that `ExposureInfo::getFilter() == Filter()` corresponds to `ExposureInfo::getFilterLabel() == nullptr` at the translator level rather than the `ExposureInfo` constructor level. This prevents spurious "\_unknown\_" `FilterLabels` from getting persisted as part of new `Exposures`.

DM-28004: ExposureInfo may persist dummy FilterLabels

---

include/lsst/afw/image/TransmissionCurve.h
src/image/ExposureFitsReader.cc
tests/test_readers.py

Note that the TransmissionCurve is special in some way and
does not work with the current implementation.

DM-28368: Fix id check so that all components can use readComponent.

---

include/lsst/afw/image/ImageBase.h
include/lsst/afw/image/lsstGil.h
python/lsst/afw/image/filterLabel.cc
python/lsst/afw/table/_schema.cc
src/detection/Footprint.cc
src/image/Image.cc
src/image/MaskedImage.cc
tests/test_filterLabel.py
tests/test_schema.py

With these fixes our use of `boost::gil` is compatible with both `boost=1.70` and `boost=1.74` which has some very aggressive boundary checks requiring slightly different iterators.

DM-27301: Fix iterator boundaries and special-case 0x0 images

---

include/lsst/afw/image/ImageBase.h
tests/statisticsSpeed.cc
ups/afw.cfg

This PR updates all (unit test) references to Boost Timer from the deprecated API to the new one. It also fixes a Doxygen error I discovered while testing.

DM-27696: Fix Boost deprecation warning in afw

---

python/lsst/afw/geom/_skyWcs.cc
python/lsst/afw/geom/_transform.cc
python/lsst/afw/geom/_transformFactory.cc

Failing to do this could lead to it not being imported and some wrappers not working.  This problem probably existed prior to the recent refactor, but was masked by higher-level code that happened to import `astshim` in at the right points.

DM-29303: Declare astshim dependency in pybind11 code that uses it.

---

python/lsst/afw/cameraGeom/_detectorCollection.py

afw.cameraGeom._detectorCollection now exports DetectorCollectionBase, DetectorCollectionBuilderBase

DM-29351: add missing package exports in afw.cameraGeom causing package-docs to fail

---

include/lsst/afw/table/Catalog.h

Instead of assuming that the catalog is always sorted, the updated `find` method first performs a binary search hoping that the catalog is sorted, and if unsuccessful, performs a brute-force linear search before declaring it unsuccessful. This fixes the bug of not finding record IDs for unsorted catalog, but fails slower for sorted catalogs.

DM-29737: Perform a brute-force search if binary search fails

---

include/lsst/afw/table/Catalog.h
src/image/PhotoCalib.cc

This PR a) fixes a few style errors introduced in a recent merge DM-29737 and b) create a log message if the catalog is found to be unsorted. The log message is to hint the user of plausible inefficiencies in finding a desired record as a result of having catalog unsorted by the Id.

DM-29775: Fix style issues introduced in DM-29737 and log output for unsorted catalogs

---

include/lsst/afw/math/Statistics.h

The methods `setNumIter` and `setNumSigmaClip` must throw an exception
if the input parameters are invalid instead of asserting that they are
valid.

Replace assert with exception for invalid argument

---

python/lsst/afw/table/_source.py
tests/test_sourceTable.py

This is essentially DM-29936 in all its aspects. The bug that caused the failure in DM-29936 was in the `meas_base` repo, and not `afw` repo. This PR puts back the commits that were reverted earlier.

DM-30105: Get children sources without repeatedly checking if the afw SourceCatalog is sorted by parent

---

include/lsst/afw/table/io/python.h
python/lsst/afw/geom/_transform.cc
python/lsst/afw/table/io/SConscript
python/lsst/afw/table/io/_inputArchive.cc
python/lsst/afw/table/io/_outputArchive.cc
src/image/MaskedImage.cc
src/table/io/OutputArchive.cc
tests/test_readers.py

[Jira ticket](https://jira.lsstcorp.org/browse/DM-28716)
[Jenkins run #34190](https://jira.lsstcorp.org/browse/DM-28716)

DM-28716: Add pybind wrapper to afw archive that handles adding set of HDUs

---

python/lsst/afw/table/catalogMatches.py

This PR adds the function `reIndexCatalog` adopted from code by @PaulPrice to apply a numpy array as an index to rows in an afw Catalog and the `matchCatalogsExact` function to use the unique combination of `(parentId, peakId, patch)` to exactly match two catalogs derived from the same `mergeDet` catalog. The main use case is to test changes in deblending and measurement algorithms on the same exact set of sources.

Add two new functions for matching and reindexing catalogs

---

.gitignore
include/lsst/afw/detection/Psf.h
include/lsst/afw/detection/python.h
python/lsst/afw/detection/_psf.cc
src/detection/Psf.cc
tests/test_gaussianPsf.py
tests/test_psf_trampoline.py

Adds `computeImageBBox`, which returns `Psf->computeImage()->getBBox()`, but allows Psf subclasses to implement this without requiring the intermediate call to `computeImage()`.
Also adds `computeKernelBBox` for symmetry, though this is equal to `computeBBox`.

DM-30426: New Psf bbox methods

---

include/lsst/afw/table/BaseTable.h
include/lsst/afw/table/Catalog.h
src/table/BaseTable.cc
tests/test_ticket22486.py

Ensure pointer to a table in a catalog is always initialized
and table contains a minimal schema

DM-22486: Ensure pointer to a table in a catalog is always initialized

---

python/lsst/afw/image/image/_fitsIoWithOptions.py
python/lsst/afw/image/image/_mask.py

Image and Mask previously always used an "image" section of the
compression options. This made it impossible to reuse the compression
settings from an Exposure without copying the relevant section to
image. This change allows the section to be explicitly specified
so that a user can declare that they want the variance settings
to be applied. Mask is changed to always prefer "mask" section
before falling back to "image".

DM-31542: Allow writeFitsWithOptions for image/mask to select the options section

---

examples/convolveLinear.cc
examples/decoratedImage.cc
examples/mask.cc
examples/maskedImageFitsIo.cc
examples/simpleConvolve.cc
examples/spatialCellExample.cc
examples/spatiallyVaryingConvolve.cc
examples/timeConvolve.cc
examples/timeWcs.cc
examples/wcsTest.cc
python/lsst/afw/table/catalogMatches.py
tests/background.cc
tests/maskedImage1.cc
tests/ramFitsIO.cc
tests/statistics.cc
tests/test_background.py
tests/test_convolve.py
tests/test_exposure.py
tests/test_fitsTables.cc
tests/test_image.py
tests/test_imageIo1.py
tests/test_mask.py
tests/test_maskedImageIO.py
tests/test_sourceMatch.py
tests/test_statistics.py
tests/test_tableArchives.cc
tests/test_tableMultiMatch.py
tests/test_warpExposure.py
tests/test_warper.py

Should use LookupError since that is compatible with C++ and
Python implementations.
Note that astrometry_net_data will never be found so this code
looks suspect.

DM-31721: Fix exception catching for getPackageDir

---

doc/lsst.afw.image/exposure-fits-metadata.rst
include/lsst/afw/coord/Observatory.h
include/lsst/afw/image/VisitInfo.h
python/lsst/afw/image/_visitInfo.cc
python/lsst/afw/image/_visitInfo.py
src/coord/Weather.cc
src/image/VisitInfo.cc
tests/test_exposure.py
tests/test_visitInfo.py
tests/test_weather.py

This PR adds C++ and Python deprecation warnings to `VisitInfo.getExposureId`, removes internal use of that method aside from tests of `VisitInfo` itself, and fixes some bugs in `VisitInfo` (in particular, a broken implementation of `operator==`; as in lsst/geom#35, simply banning NaN values is not an option) that were interfering with lsst/obs_base#396.

DM-13943: Deprecate VisitInfo.getExposureId()

---

python/lsst/afw/image/_readers.cc
tests/test_readers.py

This PR adds a pybind11 wrapper for the `ExposureFitsReader::readExposureId` method added on #613. This is necessary for correct execution of the tests on lsst/obs_base#398.

DM-32414: fix missing wrapper for ExposureFitsReader::readExposureId

---

include/lsst/afw/table/Catalog.h
python/lsst/afw/cameraGeom/utils.py
python/lsst/afw/display/interface.py
src/cameraGeom/TransformMap.cc
src/detection/Threshold.cc
src/fits.cc
src/geom/detail/frameSetUtils.cc
src/image/ExposureFitsReader.cc
src/image/ExposureInfo.cc
src/image/Mask.cc
src/image/MaskedImageFitsReader.cc
src/math/LeastSquares.cc
src/math/SpatialCell.cc
src/math/Stack.cc
src/math/detail/BasicConvolve.cc
src/math/detail/ConvolveWithInterpolation.cc
src/math/detail/KernelImagesForRegion.cc
src/math/minimize.cc
src/math/warpExposure.cc
src/table/Match.cc
src/table/io/FitsSchemaInputMapper.cc
tests/test_convolve.py
tests/test_exposure.py
tests/test_heavyFootprint.py
tests/test_kernelImagesForRegion.py
tests/test_kernelIo1.py
tests/test_leastSquares.py
tests/test_scaledPlus.py
tests/test_warpExposure.py
tests/test_warper.py

DM-31801: Use lsst prefix for loggers

---

python/lsst/afw/cameraGeom/_camera.py
python/lsst/afw/cameraGeom/_detector.py
python/lsst/afw/detection/_footprintMerge.py
python/lsst/afw/fits/_fitsContinued.py
python/lsst/afw/geom/ellipses/_axes.py
python/lsst/afw/geom/ellipses/_ellipse.py
python/lsst/afw/geom/ellipses/_quadrupole.py
python/lsst/afw/geom/polygon.py
python/lsst/afw/image/apCorrMap/_apCorrMapContinued.py
python/lsst/afw/math/_background.py
python/lsst/afw/math/_chebyshevBoundedField.py
python/lsst/afw/table/_aliasMap.py
python/lsst/afw/table/_base.py
python/lsst/afw/table/_baseColumnView.py
python/lsst/afw/table/_schema.py
python/lsst/afw/table/_schemaMapper.py
python/lsst/afw/table/_source.py
python/lsst/afw/typehandling/_SimpleGenericMap.py
tests/test_sourceTable.py

This ticket implements pure-Python methods to get PSF shapes as a `Quadrupole` object and to get the individual components of the moments and flag. Methods to get PSF shape errors and `isValid` are not implemented.

DM-30229: Add convenience methods to get PSF shape quantities

---

include/lsst/afw/table/BaseColumnView.h
include/lsst/afw/table/Catalog.h
include/lsst/afw/table/Schema.h
include/lsst/afw/table/Source.h
include/lsst/afw/table/python/catalog.h
include/lsst/afw/table/types.h
python/lsst/afw/table/_base.py
python/lsst/afw/table/_baseColumnView.cc
src/detection/FootprintSet.cc
src/table/BaseColumnView.cc
tests/test_dir.py
tests/test_sourceTable.py
tests/test_ticketDM-433.py

This reverts commit 35fc12d7ad2366282782c6c8b14b297f14270355, reversing
changes made to 538320a1dd4c9c7751cf04cf1518922b3466ebe9.
Looks like this might make gcc use too much memory for our usual build.

Revert "Merge pull request #618 from lsst/tickets/DM-32662"

---

include/lsst/afw/image/PhotoCalib.h
python/lsst/afw/image/__init__.py
python/lsst/afw/image/_photoCalib.cc
python/lsst/afw/image/_photoCalibContinued.py
tests/test_photoCalib.py

This also adds a property to know if the given photoCalib is constant (spatially-varying) or not.

DM-27106: Add array-based operations to simple photoCalib routines.

---

include/lsst/afw/image/Defect.h
include/lsst/afw/math/IntGKPData10.h
include/lsst/afw/math/Statistics.h
src/cameraGeom/Detector.cc
src/image/PhotoCalib.cc

This PR removes or rearranges Doxygen comments that were intended to be file-level but instead described namespaces.

DM-22823: Remove accidental Doxygen comments for namespaces

---

doc/lsst.afw.multiband/multiband.rst
python/lsst/afw/cameraGeom/utils.py
python/lsst/afw/image/exposure/_multiband.py

Gen3 uses band for coadds. If people want to retrieve by
physical filter it would likely need a change in API
or much more cleverness in trying to inspect the dataset type.

DM-35895: Use band for the dataId not filter

---

include/lsst/afw/fits.h
tests/test_fits.py

Fix and test case added for https://jira.lsstcorp.org/browse/DM-36207.

DM-36207: Reset the Fits object status to 0 if we are throwing an error

---

src/image/VisitInfo.cc
tests/test_visitInfo.py

Header existence checks are not sufficient because the C++ reader in PropertySet will refuse to return a string for an undefined value.

DM-36277: Check header is defined before using it for VisitInfo

---

include/lsst/afw/geom/polygon/Polygon.h
python/lsst/afw/geom/_polygon.cc
src/geom/polygon/Polygon.cc
tests/test_polygon.py

Allow checking if a polygon contains various objects like vectors of points, and a point by passing an x, y
pair instead of a Point object. Expose this to python with an auto-vectorized interface to allow passing of numpy arrays of points.

tickets/DM-36230: Add new polygon contains interface

---

include/lsst/afw/math/Statistics.h
python/lsst/afw/math/_statistics.cc
src/math/Statistics.cc
tests/test_stacker.py
tests/test_statistics.py

StatisticsStack is also useful for mosaicking coadds. Two neighboring patches will have the same exact input visits and be exact duplicates on the patch boundaries. They are 100% correlated and when stacking, then there's a genuine use case for computing variance plane as the mean of the variances. This should only be used in the very specific scenario of mosaicking coadds.

DM-34628: Add a mosaic mode option to Statistics

---

python/lsst/afw/fits/_fits.cc
python/lsst/afw/geom/_polygon.cc

Without this it is not possible to "import lsst.afw.fits" because the FitsError is not translated to python. Tests passed in afw because other parts of afw were importing pex_exceptions.

DM-37534: Ensure that pex_exceptions is imported for afw.fits

---

python/lsst/afw/image/_exposure/_exposureContinued.py
python/lsst/afw/image/_image/_image.py
python/lsst/afw/image/_maskedImage/_maskedImageContinued.py
python/lsst/afw/image/_visitInfo.py
tests/test_visitInfo.py

If this is not done a call to deepcopy goes through pickle which is very very slow.

DM-38694: Specify explicit __deepcopy__ for Exposure/Image/MaskedImage

---

include/lsst/afw/table/BaseColumnView.h
include/lsst/afw/table/python/catalog.h
include/lsst/afw/table/python/columnView.h
python/lsst/afw/table/_base.py
python/lsst/afw/table/_baseColumnView.cc
python/lsst/afw/table/_baseColumnView.py
src/table/BaseColumnView.cc
tests/test_simpleTable.py
tests/test_sourceTable.py

The overall goal here is to deprecate some duplication: ColumnView and Catalog both implement access to Flag/bool columns in different ways, and it's cleanest to just move it all to Catalog, since there's no way to actually _view_ Flag/bool column when they're stored as packed bits.

DM-39828: move Flag/bool column access from ColumnView to Catalog

---

python/lsst/afw/image/_exposureSummaryStats.py
tests/test_exposure.py

This removes warnings from reading older calexps.

DM-40739: Add column forwarding in exposure summary stats to allow decl to be renamed to dec on read.

---

python/lsst/afw/image/_exposure/_multiband.py
tests/test_multiband.py

This updates the `MultibandExposure.computePsf<Kernel>Image` methods to return a `MultibandImage`. It also adds the partial PSF to the `IncompleteDataError` so that users who try...except the error can obtain the PSF in all of the bands that were able to construct a PSF image.

DM-40451: Update MultibandExposure.computePsfImage

---

doc/lsst.afw.cameraGeom/index.rst
doc/lsst.afw.coord/index.rst
doc/lsst.afw.detection/index.rst
doc/lsst.afw.display/index.rst
doc/lsst.afw.fits/index.rst
doc/lsst.afw.formatters/index.rst
doc/lsst.afw.geom/index.rst
doc/lsst.afw.image/index.rst
doc/lsst.afw.math/index.rst
doc/lsst.afw.multiband/index.rst
doc/lsst.afw.table/index.rst
doc/lsst.afw.typehandling/index.rst
python/lsst/afw/image/exposure/exposureUtils.py
tests/test_exposure.py

This PR fixes a bug in coordinate checks that attempted to convert NaN or infinite values to integers. The bug was exposed by unit tests, but went unnoticed because it only caused a warning instead of an error.

DM-43416: Fix warning in bbox_contains_sky_coords

---

python/lsst/afw/image/testUtils.py
tests/test_methods.py

Just reporting the maximum absolute difference does not tell you where np.allclose() was failing, because it uses a relative+absolute comparison.

DM-43855: Rework error reporting for assertImagesAlmostEqual

---

src/cameraGeom/Camera.cc
src/cameraGeom/Detector.cc
tests/test_cameraGeom.py

The existing afw code assumes a simple model for the pixels->focal plane mapping and automatically sets that for each detector. This change adds a check to see whether these mappings have already been defined, and if so, skips applying the default simple model.

DM-44352: Prevent overwriting existing detector mapping

---

python/lsst/afw/image/_exposureSummaryStats.py

Persisting magnitude limit calculated in exposure summary stats.

DM-45573: Compute magnitude limit for exposure summary stats

---

src/fits.cc
tests/test_fits.py

Ensures that long keywords have HIERARCH prepended.
Otherwise, cfitsio doesn't treat them right. In particular, long string values have the CONTINUE convention messed up, and I've seen it swallow chars from the string value to put in the HIERARCH.
Includes a test that fails without this fix.

DM-47152: Writing FITS header with long keywords and long strings is broken

---

tests/test_background.py

BackgroundList is expected to behave like a Python list. It is therefore natural to expect initializing an instance with no arguments to evaluate to False.

Set the truthiness value of BackgroundList

---

src/geom/detail/frameSetUtils.cc
tests/test_exposure.py

Writing keys with '.' in them isn't advisable, but HEIRARCH permits it and we definitely don't want it to cause reading everything else to fail.

DM-47920-v28: Drop unnecessary and broken handling of dotted FITS keys in WCS reads.

---

python/lsst/afw/table/_base.py
tests/test_simpleTable.py

Other property requests will fail.

DM-49695: Allow hasattr to work for table for dunder properties if non-contiguous

---

python/lsst/afw/table/_base.py
tests/test_simpleTable.py

Other property requests will fail.

DM-49695 (v29): Allow hasattr to work for table for dunder properties if non-contiguous

---

src/geom/SkyWcs.cc

Whether a WCS is already valid FITS is a squirrely definition, because it always involves AST trying to approximate and/or simplify a non-FITS representation and that can get lucky even if the functional form is FITS-hostile.

DM-51445: Allow FITS approximations to WCSs that are alreadyt valid FITS.

---

src/geom/SkyWcs.cc

Whether a WCS is already valid FITS is a squirrely definition, because it always involves AST trying to approximate and/or simplify a non-FITS representation and that can get lucky even if the functional form is FITS-hostile.

DM-51445-v29: Allow FITS approximations to WCSs that are alreadyt valid FITS.

---

python/lsst/afw/table/_base.py
tests/test_astropyTableViews.py

There is a problem that copying a numpy array does not update wheather or not the column is read only. This commit changes the way that copy is implemented by building the astropy table and then copying the table, which is a true deep copy.

Fix SourceCatalog.asAstropy copy to make all columns writeable
